sequenceDiagram
    autonumber
    actor User
    participant ServiceAuth
    participant AuthDB

    User             ->>  ServiceAuth   :   HTTP GET http://service-auth/api/v1/users/searchuser?username=<<username>>
    ServiceAuth      ->>  AuthDB        :   find AuthEntity by username
    alt Not Found
        AuthDB       -->> ServiceAuth   :   Null
        ServiceAuth  -->> User          :   HTTP 404 Not Found
    else Found
        AuthDB       -->> ServiceAuth   :   AuthEntity
        ServiceAuth  -->> User          :   HTTP 200 OK ViewUserResponse
    end