sequenceDiagram
    autonumber
    actor User
    participant Nginx

    User            ->>  Nginx          :   HTTP GET http://libofalex.com
    Nginx           -->> User           :   HTTP 200 OK welcome.html