sequenceDiagram
    autonumber
    actor User
    participant Nginx
    participant Gateway
    participant ServiceAuth

    Note over User,ServiceAuth: User's Access Token expired, Refresh Token still valid

    User            ->>  Nginx          :   HTTP POST http://libofalex.com/refresh <br/>RefreshTokenRequest
    Nginx           ->>  Gateway        :   HTTP POST http://server-gateway/refresh <br/>RefreshTokenRequest
    Note over Gateway: REF: GF-03 Refresh Token Verification Flow
    Gateway         ->>  ServiceAuth    :   HTTP POST http://service-auth/api/v1/auth/refresh <br/>RefreshTokenRequest
    Note over ServiceAuth: REF: SF-03 Refresh Access Token Flow
    ServiceAuth     -->> Gateway        :   HTTP 200 OK RefreshTokenResponse
    Note over Gateway: REF: GF-04 Refresh Token BlackList Flow
    Gateway         -->> Nginx          :   HTTP 200 OK RefreshTokenResponse
    Nginx           -->> User           :   HTTP 200 OK RefreshTokenResponse