sequenceDiagram
    autonumber
    actor SuperUser
    participant Nginx
    participant Gateway

    SuperUser       ->>  Nginx          :   HTTP GET http://libofalex.com/provision (with Access Token)
    Nginx           ->>  Gateway        :   HTTP GET http://server-gateway/api/v1/auth/verify/hasRole?=<<UserRole>> <br/>(with Access Token)
    Note over Gateway: REF: GF-05 User Role Verification Flow
    Gateway         -->> Nginx          :   HTTP 200 OK
    Nginx           -->> SuperUser           :   HTTP 200 OK provision.html