services:
  postgres:
    image: postgres:17.5
    shm_size: 128mb
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass123
    networks:
      - libofalex

networks:
  libofalex:
    driver: bridge
